name: weather
description: "Hey there! I'm Sagnik, and this is my Flutter Weather App. It's a neat little tool that lets you check out the weather vibes for cities all around the globe. Built with love and some Flutter magic, I hope you find it useful. Dive in and let me know what you think!"

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  geolocator:
  http:
  flutter_spinkit:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900